'use client'

import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '@/app/styles/globals.css'

import { AppProviders } from '@/app/providers'

import { QueryClient } from '@tanstack/react-query'
import { auth } from '../auth'

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // const queryClient = new QueryClient();
  // const session = auth()

  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {/* <AppProviders queryClient={queryClient} session={session}> */}
        {children}
        {/* </AppProviders> */}
      </body>
    </html>
  )
}
